spring:
  config:
    import: configserver:${CONFIG_SERVER_URL}
  application:
    name: essi-client
  profiles:
    active: ${PROFILES:default}
  cloud:
    config:     
      username: ${CONFIG_SERVER_USER}
      password: ${CONFIG_SERVER_PASSWORD}
